export const Users = [
    {
      id:1,
      profilePicture: "profile/1.jpeg",
      username: "Safak Kocaoglu",
    },
    {
      id:2,
      profilePicture: "profile/2.jpeg",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "profile/3.jpeg",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "profile/4.jpeg",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "profile/5.jpeg",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "profile/6.jpeg",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "profile/7.jpeg",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "profile/8.jpeg",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "profile/9.jpeg",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "profile/10.jpeg",
      username: "Safak Kocaoglu",
    },
    {
      id:12,
      profilePicture: "profile/10.jpeg",
      username: "Safak Kocaoglu",
    },
    {
      id:13,
      profilePicture: "profile/10.jpeg",
      username: "Safak Kocaoglu",
    },
    {
      id:14,
      profilePicture: "profile/10.jpeg",
      username: "Safak Kocaoglu",
    },
    {
      id:15,
      profilePicture: "profile/10.jpeg",
      username: "Safak Kocaoglu",
    },
    {
      id:16,
      profilePicture: "profile/10.jpeg",
      username: "Safak Kocaoglu",
    },
    {
      id:17,
      profilePicture: "profile/10.jpeg",
      username: "Safak Kocaoglu",
    },
    {
      id:18,
      profilePicture: "profile/10.jpeg",
      username: "Safak Kocaoglu",
    },
    {
      id:19,
      profilePicture: "profile/10.jpeg",
      username: "Safak Kocaoglu",
    },

  ];
  
  export const posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "posts/1.jpeg",
      date: "5 mins ago",
      userId: 1,
      up: 32,
      down: 9,
    },
    {
      id: 2,
      photo: "posts/2.jpeg",
      date: "15 mins ago",
      userId: 2,
      up: 2,
      down: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "posts/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      up: 61,
      down: 2,
    },
    {
      id: 4,
      photo: "posts/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      up: 7,
      down: 3,
    },
    {
      id: 5,
      photo: "posts/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      up: 23,
      down: 5,
    },
    {
      id: 6,
      photo: "posts/6.jpeg",
      date: "1 day ago",
      userId: 6,
      up: 44,
      down: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "posts/7.jpeg",
      date: "2 days ago",
      userId: 7,
      up: 52,
      down: 3,
    },
    {
      id: 8,
      photo: "posts/8.jpeg",
      date: "3 days ago",
      userId: 8,
      up: 15,
      down: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "posts/9.jpeg",
      date: "5 days ago",
      userId: 9,
      up: 11,
      down: 2,
    },
    {
      id: 10,
      photo: "posts/10.jpeg",
      date: "1 week ago",
      userId: 10,
      up: 104,
      down: 12,
    },
  ];